import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'
import joshua from "./joshua-edo.jpg";


  const currentYear = new Date().getFullYear();
  const currentAge = currentYear - 2002;
  
const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
    <div className="Hero container">
      <div className="row">
        <div className="col w-100 d-block d-lg-inline">
          <img src={joshua} alt="joshua edo" className="hero--img" />
        </div>
        <div className="col w-100 d-block d-lg-inline">
          <blockquote className="quote">
            <i>
              {" "}
              “The most innovative solution to a complex problem is often the
              simplest one. But as anyone who’s devoted their time to big ideas
              knows, simple and easy are two very different things.”
            </i>
          </blockquote>
          <p className="quote"> - Mackey Saturday</p>

          <p className="bio">
            My name is Joshua. I’m a {currentAge} year old frontend web
            developer living in West Africa, Nigeria. I love Dan Brown's books,
            Chelsea Football Club, How I met your mother, documentaries, pizza,
            solving complex problems, and silence.
          </p>
        </div>
      </div>
    </div>


      </main>
    </>
  )
}
